GET http://localhost:5000/public

###
POST  http://localhost:5000/public

###
PATCH  http://localhost:5000/public/15

###
DELETE   http://localhost:5000/public/12

###

POST http://localhost:5000/auth/login 
Content-Type: application/json

{
"username": "bondhon"
}

### 
GET http://localhost:5000/auth/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9uZGhvbiIsImlhdCI6MTY3MjMxMzQ3NywiZXhwIjoxNjcyMzEzNTM3fQ.7CKTIS81tSf6i8IwNaRWXtZ3OggVHNnJBLZ1vvCypR8

###
DELETE http://localhost:5000/auth/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9uZGhvbiIsImlhdCI6MTY3MjMxMzUxMX0.3slgnEdrC0oCYoGhG21zlY-vBnUd-1bUvhfhPfnGHUo"
}

###

POST http://localhost:5000/auth/token 
Content-Type: application/json

{
"token":
 "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9uZGhvbiIsImlhdCI6MTY3MjMxMzU5NH0.aGA5iYr6QiB9S5QN0xkD2bu64aO3FaNV0gW3xDH8wwU"
}